; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200

board_build.filesystem = littlefs
lib_ldf_mode=deep

build_flags =
  -DCORE_DEBUG_LEVEL=5
  -DEASYWIFI_LITTLEFS

lib_deps = 
  jgromes/RadioLib@^7.1.2 ;Lib for lora radio
  https://github.com/Arthur5492/HotButton.git ;button
  esp32async/ESPAsyncWebServer@^3.7.4 ;For printing purpose
  https://github.com/PaulStoffregen/Time.git ;Get actual time for log purpose
  https://github.com/Arthur5492/EasyWiFi-ESP32.git ;TO connect to wifi